### ISSUE TITLE
exclude-from-classmap in autoload

### ISSUE THREAD

**Issue by koekaverna** [shipmonk-rnd/composer-dependency-analyser#136]
Hi, first of all I want to say thank you for this awesome tool!

I found that in composer.json autoload section there is a section "[exclude-from-classmap](https://getcomposer.org/doc/04-schema.md#exclude-files-from-classmaps)" that can be helpfull to exclude tests for example.

Is it possible to add this logic to this tool?
I work with legacy project and in my case some tests is in subfolder Test of project feature folders.

Example
MyProject\Library\FeatureXyz\
MyProject\Library\FeatureXyz\Tests\

**Comment by janedbal** [comment]
It is theoretically possible to implement, but you can use `$config->addPathToExclude(__DIR__ . '/Feature/tests')` even now to achieve the same thing.

**Comment by koekaverna** [comment]
> addPathToExclude

As I can see it's not support any patterns matching, in my scenario I have 100 folders like this :-)

**Comment by janedbal** [comment]
You can easily do some glob within the php config file, we are doing the same thing:

```php
$config->addPathsToExclude(\Webmozart\Glob\Glob::glob(__DIR__ . '/bin/*.php'));
```
