### ISSUE TITLE
False positive unused-package with stevegrunwell/time-constants package

### ISSUE THREAD

**Issue by mad-briller** [shipmonk-rnd/composer-dependency-analyser#137]
When analysing a codebase that uses [this package](https://github.com/stevegrunwell/time-constants) it is incorrectly flagged as unused despite the constants it defines being used.

**Comment by janedbal** [comment]
PHP offers **no API how to retrieve where a global constant was declared**. Thus, we cannot detect the package where it comes from and mark such package as used.

So sadly, this is impossible to solve (if we want to keep this level of performance)

**Comment by mad-briller** [comment]
i suspected that might be the case, thanks for confirming

**Comment by janedbal** [comment]
For a reference, this limitation may change in some future PHP release, there is even [open PR now](https://github.com/php/php-src/pull/15847/files).
