### ISSUE TITLE
Detect suggested packages

### ISSUE THREAD

**Issue by alexhampu** [shipmonk-rnd/composer-dependency-analyser#138]
Hello,

Foremost, this is a wonderful package and really fast.

With Laravel we have packages that are suggested in composer.json, which if required in the project's composer.json are used directly by Laravel. This package doesn't detect suggested packages and marks them as unused, even though they are used at runtime.

For example `doctrine/dbal` is suggested in the `composer.json` of ``laravel/framework``, if installed in the project it will be used by Laravel.

Any plans of doing this?

Best regards,
Alex!

**Comment by janedbal** [comment]
Thanks for suggestion, but we are not planning such feature yet.
