### ISSUE TITLE
Add support for scanning inside Symfony's bundles.php

### ISSUE THREAD

**Issue by ruudk** [shipmonk-rnd/composer-dependency-analyser#146]
In my Symfony Application, we have a `config/bundles.php` that looks like this:

```php
<?php

declare(strict_types=1);

return [
    Symfonycasts\TailwindBundle\SymfonycastsTailwindBundle::class => ['all' => true],
    Symfony\UX\StimulusBundle\StimulusBundle::class => ['all' => true],
];
```

My configuration looks like this:
```php
<?php

use ShipMonk\ComposerDependencyAnalyser\Config\Configuration;

$config = new Configuration();
$config->addPathToScan(__DIR__ . '/config/bundles.php', isDev: false);

return $config;
```

But even though those bundles are used, the analyzer complains:

```command
$ vendor/bin/composer-dependency-analyser

Using config composer-dependency-analyser.php

Found unused dependencies!
(those are listed in composer.json, but no usage was found in scanned paths)

  • symfony/stimulus-bundle
  • symfonycasts/tailwind-bundle
```

Am I missing something, or is a FQCN class reference not seen as usage?

**Comment by janedbal** [comment]
Files without namespace and use statements have limited support [as stated in readme](https://github.com/shipmonk-rnd/composer-dependency-analyser?tab=readme-ov-file#limitations). So just use FQN or use statements.

**Comment by ruudk** [comment]
@janedbal Hmm, interesting. When you have a bundles.php file with 50 bundles, having to import all them, makes the file 100+ lines instead of 50 lines. So I would prefer not to have to do that.

Would it be possible to improve this limit support?

**Comment by ruudk** [comment]
If it is, I could try to provide a PR for it.

**Comment by janedbal** [comment]
> When you have a bundles.php file with 50 bundles, having to import all them, makes the file 100+ lines instead of 50 lines. So I would prefer not to have to do that.

So use FQN like this:

```php
<?php

return [
    \Symfonycasts\TailwindBundle\SymfonycastsTailwindBundle::class => ['all' => true],
    \Symfony\UX\StimulusBundle\StimulusBundle::class => ['all' => true],
];
```

> Would it be possible to improve this limited support?

Definitelly not easy. I'll try to think about that again.

**Comment by ruudk** [comment]
> So use FQN like this:
> 
> ```
> <?php
> 
> return [
>     \Symfonycasts\TailwindBundle\SymfonycastsTailwindBundle::class => ['all' => true],
>     \Symfony\UX\StimulusBundle\StimulusBundle::class => ['all' => true],
> ];
> ```

That works, although PHPStorm / PHP CS Fixer now automatically imports it. Not ideal.

**Comment by janedbal** [comment]
Ok, I dived into it and turns out it was quite easy (#148). 

Can you try `dev-master` if that works for you? Thanks

**Comment by ruudk** [comment]
@janedbal It works 🎉 ⚡  Thank you!!

**Comment by ruudk** [comment]
If you have time, it would be great to have it tagged too.
