### ISSUE TITLE
Sudden problem with unknown class `PhpParser\Node\Stmt\Throw_`

### ISSUE THREAD

**Issue by ruudk** [shipmonk-rnd/composer-dependency-analyser#162]
Somehow, from one day to another, `composer-dependency-analyser` started to fail with this error.

```command
$ vendor/bin/composer-dependency-analyser

Error: Using config composer-dependency-analyser.php

Unknown classes!
(unable to autoload those, so we cannot check them)

  • PhpParser\Node\Stmt\Throw_
    in src-dev/PHPStan/Rule/NoCatchThemAllWithoutTrackingRule.php:92


(scanned 18486 files in 1.937 s)

```

It's tripping over this line:
```php
    /**
     * @param array<Node\Stmt> $stmts
     */
    private function isHandled(Scope $scope, Node\Expr\Variable $var, array $stmts) : bool
    {
        foreach ($stmts as $stmt) {
            if ($stmt instanceof Node\Stmt\Throw_) {  // <!--- 
                $expr = $stmt->expr;
                if ( ! $expr instanceof Node\Expr\CallLike) {
                    continue;
                }
```

Before, we had the following configuration to exclude `SHADOW_DEPENDENCY`. 
```php
$config->ignoreErrorsOnPackageAndPath('nikic/php-parser', __DIR__ . '/src-dev/PHPStan', [ErrorType::SHADOW_DEPENDENCY]);
$config->ignoreErrorsOnPackageAndPath('nikic/php-parser', __DIR__ . '/src-dev/Rector', [ErrorType::SHADOW_DEPENDENCY]);
```

This worked fine.

Then this morning, we saw the error above. 

I even tried to manually require `nikic/php-parser` as a dev dependency. That didn't work either.

Could it be that this is a bug in this analyzer?

I cannot reproduce the error locally. The error only pops up on our GitHub Actions CI running with the following versions:

- PHP 8.3.9
- Composer 2.7.7

**Comment by janedbal** [comment]
The important thing about `nikic/php-parser` is that it is typically located **twice** in your codebase (if you use PHPStan):
- once as regular (or transitive dependency) in `vendor/nikic/php-parser`
- once as bundled dependency of PHPStan in `vendor/phpstan/phpstan/phpstan.phar/vendor/nikic/php-parser`


Looking at the error, it is related to [removal](https://github.com/nikic/PHP-Parser/blob/master/UPGRADE-5.0.md#changes-to-the-throw-representation) of `Stmt\Throw_` in `nikic/php-parser` version 5.x.


So I believe this is what happened:
- your regular dependency got upgraded to v5
- composer-dependency-analyser starts reporting non-existing class (as it is NOT present in regular composer's autoloader)
- PHPStan execution is not affected as it still uses v4 and has its own parser bundled inside its phar


What can you do about it?
- You can ignore it
- You can hook both autoloaders to composer-dependency analyser [as we do](https://github.com/shipmonk-rnd/phpstan-rules/blob/d3a6576/composer-dependency-analyser.php#L8)

**Comment by ruudk** [comment]
Thanks @janedbal for the detailed response.

I feel silly now for not knowing this. I still don't understand how it could suddenly break without a Composer update in-between. I also don't know why it locally works for me, while it doesn't on CI.

> You can hook both autoloaders to composer-dependency analyser [as we do](https://github.com/shipmonk-rnd/phpstan-rules/blob/d3a6576/composer-dependency-analyser.php#L8)

I applied this and it works now! Thanks 🎉

**Comment by janedbal** [comment]
I dont think I'm able to answer those questions without seeing the project :)

**Comment by ruudk** [comment]
I understand. We can close this now as there is a good solution. Thanks again! 🎉

**Comment by janedbal** [comment]
> there is a good solution.

Be careful. There is no good solution imo. The root cause is still there. The lib is there twice and prepending PHPStan's classloader just prioritizes his dependencies. For regular application codebase, one may consider ignore (within PHPStan-related folder) more "proper" solution.

We used autoload prepend in the linked case because the package is actually PHPStan extension (set of rules).

**Comment by ruudk** [comment]
I changed it to:
```php
$config->addPathToExclude(__DIR__ . '/src-dev/PHPStan');
$config->addPathToExclude(__DIR__ . '/src-dev/Rector');
```

And it works as well. I agree this is a better approach.
