### ISSUE TITLE
Usage of Polyfilled Function Not Detected

### ISSUE THREAD

**Issue by Murl08** [shipmonk-rnd/composer-dependency-analyser#202]
It seems the actual usage of a polyfilled function like [`array_is_list()`](https://www.php.net/manual/de/function.array-is-list.php)  from [`symfony/polyfill-php81`](https://packagist.org/packages/symfony/polyfill-php81) does not get detected correctly by Composer Dependency Analyser.

Snippet of our `composer.json` containing the polyfill library:

```` json
{
    "require": {
        "php": ">=7.4",
        "symfony/polyfill-php81": "^1.31"
    },
    "config": {
        "platform": {
            "php": "7.4.33"
        },
    }
}
````

Our PHP version, which does not contain the called (but polyfilled) function:
```` shell
php -v
PHP 7.4.33 (cli) (built: Nov  2 2022 16:00:55) ( ZTS Visual C++ 2017 x64 )
Copyright (c) The PHP Group
Zend Engine v3.4.0, Copyright (c) Zend Technologies
    with Xdebug v3.1.6, Copyright (c) 2002-2022, by Derick Rethans
````

Snippet of our calling code:

```` php
array_is_list($array);
````

Snippet of Composer Dependency Analyser output:
```` 
Found 1 unused dependency!
(those are listed in composer.json, but no usage was found in scanned paths)

  • symfony/polyfill-php81
````

The version of the tool:

Composer Dependency Analyser 1.8.1 (0acd9d94be4d9397055ff012d0abf2ae88072e99)

**Comment by yguedidi** [comment]
I have the same issue with the package [iamcal/lib_autolink](https://github.com/iamcal/lib_autolink) that [exposes](https://github.com/iamcal/lib_autolink/blob/master/composer.json#L6) only functions

**Comment by yguedidi** [comment]
Thanks @janedbal
