### ISSUE TITLE
Class constant called SESSION_ID reported as shadow dependency

### ISSUE THREAD

**Issue by spaze** [shipmonk-rnd/composer-dependency-analyser#203]
Analyzing my codebase with 1.8.1, the following is reported:

```
Found 1 shadow dependency!
(those are used, but not listed as dependency in composer.json)

  • ext-session
      SESSION_ID
        src/EasterEgg/PhpInfoCookieSanitization.php:9
```

but the `SESSION_ID` is a class constant, see [the source](https://github.com/spaze/michalspacek.cz/blob/266487d2ddc6f15bb8ef5bde90fc87cb7e3f3234/app/src/EasterEgg/PhpInfoCookieSanitization.php#L9):

```php
class PhpInfoCookieSanitization
{

	public const string SESSION_ID = '...';
...
```

I can of course rename the class constant, or ignore the error, but I think it maybe shouldn't be reported.

**Comment by janedbal** [comment]
Thank you for your report, fixed in [1.8.2](https://github.com/shipmonk-rnd/composer-dependency-analyser/releases/tag/1.8.2)
