### ISSUE TITLE
why is the tool so fast?

### ISSUE THREAD

**Issue by staabm** [shipmonk-rnd/composer-dependency-analyser#207]
without looking much into the codebase, I was wondering why/how it can be so fast (e.g. in comparison to composer-unused)

whats the secret sauce? :)

**Comment by janedbal** [comment]
In short, we do not use AST, but just tokens for all the analysis.

Here are some older slides about it: https://docs.google.com/presentation/d/1CbAR_iXUbjIYmvYzh5oXuKs3PwiiI1ZYi28ASI2h_EQ/edit?usp=drivesdk

**Comment by staabm** [comment]
awesome, thanks for the pointer and the slides.
