### ISSUE TITLE
Missing support for subdirectories of autoload listed in autoload-dev 

### ISSUE THREAD

**Issue by chrif** [shipmonk-rnd/composer-dependency-analyser#54]
Our prod and dev code is all in "src", divided in multiple (about a hundred) modules, and each module has a "Tests" folder where all the dev only code reside. The autoload section contains something like:

```
"autoload": {
    "psr-4": {
      "App\\": [
        "src/"
      ],
    }
  },
```

and autoload-dev contains:

```
"autoload-dev": {
    "psr-4": {
      "App\\Module1\\Tests\\": "src/Module1/Tests/",
      "App\\Module2\\Tests\\": "src/Module2/Tests/",
      "App\\Module3\\Tests\\": "src/Module3/Tests/",
       ...
      }
  },
```

Right now, dependencies used only in Tests folders are reported as dev dependencies found in production code. I couldn't find a way to remove these false positives, even with the PHP config. Is it possible? I can't add as prod code all the subdirectories of each module except the Tests folders. It is not practical.

**Comment by janedbal** [comment]
This is already fixed in `dev-master` (by #52), I also added test for this specific usecase in #55. But this can get more complicated and this package should use the same path merging strategy as composer do, so I'll check this more deeply if we comply with that before closing this issue.

Thanks for your report!

**Comment by janedbal** [comment]
It looks correct. I'll soon release `1.2.0` containing the fix.

**Comment by janedbal** [comment]
Version [1.2.0](https://github.com/shipmonk-rnd/composer-dependency-analyser/releases/tag/1.2.0) no longer suffers this issue.

**Comment by chrif** [comment]
It works! Thank you.
