### ISSUE TITLE
Cannot add a file without extension as a path to scan

### ISSUE THREAD

**Issue by chrif** [shipmonk-rnd/composer-dependency-analyser#61]
We have a file named `application/console`, and when I add it to the paths to scan, it fails with this error:
`Unable to list files in /app/application/console`

It looks like a file without extension is automatically assumed to be a directory.

**Comment by janedbal** [comment]
Fixed in [1.2.1](https://github.com/shipmonk-rnd/composer-dependency-analyser/releases/tag/1.2.1)

**Comment by chrif** [comment]
It works. Thanks.
