### ISSUE TITLE
Support functions detection

### ISSUE THREAD

**Issue by simPod** [shipmonk-rnd/composer-dependency-analyser#67]
When using exported functions like `iterable_to_array()` from https://packagist.org/packages/bentools/iterable-functions, those packages are marked as unused. Is it possible to add the detection?

**Comment by janedbal** [comment]
So far, this is known limitation mentioned in readme:

> Function and constant usages are not analysed
Therefore, if some package contains only functions, it will be reported as unused

I have few ideas how to implement that, but I'm not sure those will be viable...

**Comment by simPod** [comment]
Understand.

Thanks for the great tool anyways, exceeded expectations!

**Comment by janedbal** [comment]
Implemented, ready in [1.5.0](https://github.com/shipmonk-rnd/composer-dependency-analyser/releases/tag/1.5.0) :tada:
