### ISSUE TITLE
Found unused dependencies

### ISSUE THREAD

**Issue by gemal** [shipmonk-rnd/composer-dependency-analyser#83]
Love your tool but wants to better understand why I have a lot of packages being reported as "Found unused dependencies"

Fx "snscripts/itc-reporter"
https://github.com/mikebarlow/itc-reporter

In my code I have:
`use Snscripts\ITCReporter\Reporter;`

is this because of a bug in snscripts or ?

Same properly with `matomo/device-detector`
where my code is:
`use DeviceDetector\DeviceDetector;`

anything you can do with this or?

I'm running with "dev-master" code

**Comment by janedbal** [comment]
Use statements are not considered as a usage (as those might be dead without any usage in the file). How does the class reference (the real usage) look in the file?

**Comment by gemal** [comment]
> Use statements are not considered as a usage (as those might be dead without any usage in the file). How does the class reference (the real usage) look in the file?

`$Reporter = new Reporter(new Client());`

It's also being reported as unused with:
```
Snscripts\ITCReporter\Reporter
app\src\Command\AdminReportCommand.php:328
```

**Comment by janedbal** [comment]
Are you sure those paths are checked? This tool uses your composer autoload paths. 

If the usage is not among them, you need to add more paths [via configuration file](https://github.com/shipmonk-rnd/composer-dependency-analyser?tab=readme-ov-file#configuration):

```php
<?php

use ShipMonk\ComposerDependencyAnalyser\Config\Configuration;
use ShipMonk\ComposerDependencyAnalyser\Config\ErrorType;

$config = new Configuration();

return $config
    ->addPathToScan(__DIR__ . '/src', isDev: false)
```

**Comment by gemal** [comment]
OK. I was not aware of this
