### ISSUE TITLE
Found dev dependencies in production code

### ISSUE THREAD

**Issue by gemal** [shipmonk-rnd/composer-dependency-analyser#84]
I have the following setup in the config file:
```
    ->addPathToScan(__DIR__ . '/app/src', false)
    ->addPathToScan(__DIR__ . '/app/src/TestSuite', true)
```

But I get a section like this in the output:
```
Found dev dependencies in production code
  • phpunit/phpunit
      PHPUnit\Framework\Assert
        app\src\TestSuite\CommonAssertionsTrait.php:34
        app\src\TestSuite\CommonAssertionsTrait.php:53
        app\src\TestSuite\CommonAssertionsTrait.php:70
```

shouldn't those be ignore as production code?

I've tried to run in on both Windows and Linux and same result

**Comment by janedbal** [comment]
This should work, [there is a testcase for this](https://github.com/shipmonk-rnd/composer-dependency-analyser/blob/e13b952/tests/AnalyserTest.php#L507-L530).

Theoretically, the path can be overwritten by the paths added from your `composer.json` autoload paths. Those are added after your config is executed. 


If you want to set all paths manually, you can use:

```php
$config->disableComposerAutoloadPathScan()
```

**Comment by janedbal** [comment]
I'd not call it a bug, just the last mark (prod/dev) of a path wins.

```php
$config
    ->addPathToScan(__DIR__ . '/app/src', false)          // src/TestSuite is prod
    ->addPathToScan(__DIR__ . '/app/src/TestSuite', true) // src/TestSuite is dev
    ->addPathToScan(__DIR__ . '/app/src', false)          // src/TestSuite is prod again
```

But the visibility into what is beeing scanned is not good, I'll add some output saying which paths are scanned.

**Comment by JanTvrdik** [comment]
@janedbal How about processing the paths from shortest to longest?
